=== jixxed/ed-odyssey-materials-helper/application/src/main/resources/schemas/capi/squadron/squadron.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CapiSquadron",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "tag": {
      "type": "string"
    },
    "ownerId": {
      "type": "integer"
    },
    "platform": {
      "type": "string"
    },
    "created": {
      "type": "string"
    },
    "acceptingNewMembers": {
      "type": "integer"
    },
    "powerId": {
      "type": [
        "integer",
        "null"
      ]
    },
    "powerName": {
      "type": "string"
    },
    "superpowerId": {
      "type": "integer"
    },
    "superpowerName": {
      "type": "string"
    },
    "factionId": {
      "type": "integer"
    },
    "factionName": {
      "type": "string"
    },
    "factionHomeSystemId": {
      "type": "integer"
    },
    "factionHomeSystemName": {
      "type": "string"
    },
    "userTags": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "memberCount": {
      "type": "integer"
    },
    "full": {
      "type": "integer"
    },
    "description": {
      "type": "string"
    },
    "motto": {
      "type": "string"
    },
    "isMentoring": {
      "type": "boolean"
    },
    "perks": {
      "type": "object",
      "properties": {
        "primary": {
          "type": "string"
        },
        "secondary": {
          "type": "string"
        },
        "cooldowns": {
          "type": "object",
          "properties": {
            "primary": {
              "type": "integer"
            },
            "secondary": {
              "type": "integer"
            }
          },
          "required": [
            "primary",
            "secondary"
          ]
        }
      },
      "required": [
        "primary",
        "secondary",
        "cooldowns"
      ]
    },
    "active7Days": {
      "type": "integer"
    },
    "active30Days": {
      "type": "integer"
    },
    "squadronCarrier": {
      "type": "object",
      "$ref": "../fleetcarrier/fleetcarrier.json"
    },
    "members": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "squadron_id": {
            "type": "integer"
          },
          "member_id": {
            "type": "integer"
          },
          "joined": {
            "type": "string"
          },
          "expires_ts": {
            "type": "integer"
          },
          "status": {
            "type": "string"
          },
          "requested": {
            "type": "string"
          },
          "requested_ts": {
            "type": "integer"
          },
          "rank_id": {
            "type": "integer"
          },
          "requestletter": {
            "type": [
              "string",
              "null"
            ]
          },
          "credit_contributions": {
            "type": "integer"
          },
          "presence": {
            "type": "boolean"
          },
          "biography": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          },
          "user_id": {
            "type": "integer"
          },
          "rankCombat": {
            "type": "integer"
          },
          "rankExplore": {
            "type": "integer"
          },
          "rankTrade": {
            "type": "integer"
          },
          "rankCqc": {
            "type": "integer"
          },
          "soldierRank": {
            "type": "integer"
          },
          "exobiologistRank": {
            "type": "integer"
          },
          "empireRank": {
            "type": "integer"
          },
          "federationRank": {
            "type": "integer"
          },
          "powerRank": {
            "type": [
              "integer",
              "null"
            ]
          },
          "powerId": {
            "type": [
              "integer",
              "null"
            ]
          },
          "lastOnline": {
            "type": "string"
          },
          "lastOnline_ts": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "lastLocationId": {
            "type": "integer"
          },
          "lastLocation": {
            "type": "string"
          },
          "shipName": {
            "type": "string"
          },
          "shipModel": {
            "type": "string"
          },
          "userPlayTime": {
            "type": "integer"
          },
          "systemAddr": {
            "type": "integer"
          },
          "avatarXML": {
            "type": "string"
          }
        },
        "required": [
          "squadron_id",
          "member_id",
          "joined",
          "expires_ts",
          "status",
          "requested",
          "requested_ts",
          "rank_id",
          "credit_contributions",
          "presence",
          "biography",
          "user_id",
          "rankCombat",
          "rankExplore",
          "rankTrade",
          "rankCqc",
          "soldierRank",
          "exobiologistRank",
          "empireRank",
          "federationRank",
          "lastOnline",
          "lastOnline_ts",
          "name",
          "lastLocationId",
          "lastLocation",
          "shipName",
          "shipModel",
          "userPlayTime",
          "systemAddr"
        ]
      }
    },
    "bank": {
      "type": "object",
      "properties": {
        "credits": {
          "type": "object",
          "existingJavaType": "java.util.Map<String,BankItem[]>"
        },
        "commodities": {
          "type": "object",
          "existingJavaType": "java.util.Map<String,BankItem[]>"
        },
        "microresources": {
          "type": "object",
          "existingJavaType": "java.util.Map<String,BankItem[]>"
        },
        "ships": {
          "type": "object",
          "existingJavaType": "java.util.Map<String,ShipItem[]>"
        }
      },
      "required": [
        "credits"
      ]
    }
  },
  "required": [
    "id",
    "name",
    "tag",
    "ownerId",
    "platform",
    "created",
    "acceptingNewMembers",
    "powerId",
    "powerName",
    "superpowerId",
    "superpowerName",
    "factionId",
    "factionName",
    "factionHomeSystemId",
    "factionHomeSystemName",
    "userTags",
    "memberCount",
    "full",
    "description",
    "motto",
    "isMentoring",
    "perks",
    "active7Days",
    "active30Days",
    "squadronCarrier",
    "members",
    "bank"
  ]
}

=== jixxed/ed-odyssey-materials-helper/application/src/test/resources/parser/capisquadron/squadron.json
{"id":74416,"name":"ODYSSEY MATERIAL HELPERS","tag":"ODMH","ownerId":5352618,"platform":"PC","created":"2022-03-21 10:12:28","acceptingNewMembers":1,"powerId":null,"powerName":"","superpowerId":4,"superpowerName":"Independent","factionId":108093660155225465,"factionName":"Materia Auxiliatores","factionHomeSystemId":7269098333561,"factionHomeSystemName":"Harow","userTags":[7,12,16,17,18,19,25,26,33,6],"memberCount":14,"full":0,"description":"Get rich quick or die trying","motto":"MONEY, MONEY, MONEY, MONEY, MONEY, MONEY, MONEY","isMentoring":false,"perks":{"primary":"bonusMiningFragment","secondary":"powerplayMerits","cooldowns":{"primary":1755707841,"secondary":1755707841}},"active7Days":0,"active30Days":5,"squadronCarrier":{"name":{"callsign":"ODMH","vanityName":"504c4154494e554d204d454d42455253204f4e4c59","filteredVanityName":"504c4154494e554d204d454d42455253204f4e4c59"},"currentStarSystem":"LHS 3388","balance":"717006066","fuel":"1000","state":"normalOperation","theme":"Miner","dockingAccess":"squadron","notoriousAccess":false,"capacity":{"shipPacks":0,"modulePacks":0,"cargoForSale":0,"cargoNotForSale":0,"cargoSpaceReserved":0,"crew":5800,"freeSpace":44816,"microresourceCapacityTotal":1000,"microresourceCapacityFree":1000,"microresourceCapacityUsed":0,"microresourceCapacityReserved":0,"squadronBankTotal":9384},"itinerary":{"completed":[{"departureTime":"2025-08-20 11:54:00","arrivalTime":"2025-08-20 11:15:33","state":"success","visitDurationSeconds":2307,"starsystem":"Nzam Cimi"},{"departureTime":"2025-08-21 20:47:00","arrivalTime":"2025-08-20 11:54:00","state":"success","visitDurationSeconds":118380,"starsystem":"LHS 3388"},{"departureTime":"2025-08-21 21:38:00","arrivalTime":"2025-08-21 20:47:00","state":"success","visitDurationSeconds":3060,"starsystem":"Palee"},{"departureTime":null,"arrivalTime":"2025-08-21 21:38:00","state":"success","visitDurationSeconds":336099,"starsystem":"LHS 3388"}],"totalDistanceJumpedLY":138,"currentJump":null},"marketFinances":{"cargoTotalValue":0,"allTimeProfit":0,"numCommodsForSale":0,"numCommodsPurchaseOrders":0,"balanceAllocForPurchaseOrders":0},"blackmarketFinances":{"cargoTotalValue":0,"allTimeProfit":0,"numCommodsForSale":0,"numCommodsPurchaseOrders":0,"balanceAllocForPurchaseOrders":0},"finance":{"bankBalance":717006066,"bankReservedBalance":0,"taxation":0,"service_taxation":{"bartender":0,"pioneersupplies":0,"rearm":0,"refuel":0,"repair":0,"shipyard":0,"outfitting":0},"numServices":9,"numOptionalServices":0,"debtThreshold":-300000000,"maintenance":20816043,"maintenanceToDate":16762058,"coreCost":10000000,"servicesCost":10416043,"servicesCostToDate":6362058,"jumpsCost":400000,"numJumps":2,"bartender":{"microresourcesTotalValue":0,"allTimeProfit":0,"microresourcesForSale":0,"microresourcesPurchaseOrders":0,"balanceAllocForPurchaseOrders":0,"profitHistory":[0,0,0,0,0,0,0,0]}},"servicesCrew":{"shipyard":{"crewMember":{"name":"Lilliana Hoover","gender":"F","enabled":"YES","faction":"none","salary":0,"hiringPrice":null,"lastEdit":"2025-08-20 11:15:33"},"invoicesWeekToDate":[{"wages":0,"from":"2025-08-20 11:15:33","until":"2025-08-25 18:59:38","type":"current"},{"wages":0,"from":"2025-08-25 18:59:38","until":"2025-08-28 07:00:00","type":"expected"}],"status":"ok"},"refuel":{"crewMember":{"name":"Kaylani Estes","gender":"F","enabled":"YES","faction":"none","salary":1500000,"hiringPrice":40000000,"lastEdit":"2025-08-21 20:49:19"},"invoicesWeekToDate":[{"wages":840820,"from":"2025-08-21 20:49:19","until":"2025-08-25 18:59:38","type":"current"},{"wages":1376589,"from":"2025-08-25 18:59:38","until":"2025-08-28 07:00:00","type":"expected"}],"status":"ok"},"repair":{"crewMember":{"name":"Larissa Hancock","gender":"F","enabled":"YES","faction":"none","salary":1500000,"hiringPrice":50000000,"lastEdit":"2025-08-21 20:49:21"},"invoicesWeekToDate":[{"wages":840815,"from":"2025-08-21 20:49:21","until":"2025-08-25 18:59:38","type":"current"},{"wages":1376584,"from":"2025-08-25 18:59:38","until":"2025-08-28 07:00:00","type":"expected"}],"status":"ok"},"rearm":{"crewMember":{"name":"Kayden Pierce","gender":"F","enabled":"YES","faction":"none","salary":1500000,"hiringPrice":95000000,"lastEdit":"2025-08-21 20:49:23"},"invoicesWeekToDate":[{"wages":840811,"from":"2025-08-21 20:49:23","until":"2025-08-25 18:59:38","type":"current"},{"wages":1376579,"from":"2025-08-25 18:59:38","until":"2025-08-28 07:00:00","type":"expected"}],"status":"ok"},"outfitting":{"crewMember":{"name":"Bryanna Mitchell","gender":"F","enabled":"YES","faction":"none","salary":5000000,"hiringPrice":250000000,"lastEdit":"2025-08-21 20:49:31"},"invoicesWeekToDate":[{"wages":2802645,"from":"2025-08-21 20:49:31","until":"2025-08-25 18:59:38","type":"current"},{"wages":4588533,"from":"2025-08-25 18:59:38","until":"2025-08-28 07:00:00","type":"expected"}],"status":"ok"},"exploration":{"crewMember":{"name":"Joelle Mcgowan","gender":"F","enabled":"YES","faction":"none","salary":1850000,"hiringPrice":150000000,"lastEdit":"2025-08-21 20:49:32"},"invoicesWeekToDate":[{"wages":1036972,"from":"2025-08-21 20:49:32","until":"2025-08-25 18:59:38","type":"current"},{"wages":1697754,"from":"2025-08-25 18:59:38","until":"2025-08-28 07:00:00","type":"expected"}],"status":"ok"}},"cargo":[],"orders":{"commodities":{"sales":[],"purchases":[]},"onfootmicroresources":{"sales":[],"purchases":[]}},"carrierLocker":{"assets":[],"goods":[],"data":[]},"reputation":[{"majorFaction":"empire","score":100},{"majorFaction":"federation","score":100},{"majorFaction":"independent","score":100},{"majorFaction":"alliance","score":100}]},"members":[{"squadron_id":74416,"member_id":300407,"joined":"2022-10-10 06:33:09","expires_ts":1667975589,"status":"MEMBER","requested":"2022-10-10 06:32:39","requested_ts":1665383559,"rank_id":1,"requestletter":"48692074686572652E20492764206C696B6520746F206A6F696E20796F7572207371756164726F6E2E","credit_contributions":0,"presence":false,"biography":"","user_id":212462,"rankCombat":8,"rankExplore":8,"rankTrade":10,"rankCqc":0,"soldierRank":5,"exobiologistRank":5,"empireRank":12,"federationRank":14,"powerRank":null,"powerId":null,"lastOnline":"2025-08-19 23:38:35","lastOnline_ts":1755646715,"name":"53697269757320536b72696c69756d","lastLocationId":7269098333561,"lastLocation":"4861726f77202d204b39562d32385a","shipName":"The Boatman","shipModel":"Type-9 Heavy","userPlayTime":188943,"systemAddr":7269098333561,"avatarXML":"\"<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<XMLResDocument version=\"1\">\n\t<AvatarSettings symbol=\"\">\n\t\t<AvatarSettingName><\/AvatarSettingName>\n\t\t<AvatarClass>playeravatar_female<\/AvatarClass>\n\t\t<ComplexionType>ComplexionSmooth<\/ComplexionType>\n\t\t<ModelSwapFeatures>\n\t\t\t<item>\n\t\t\t\t<Feature>Hair<\/Feature>\n\t\t\t\t<Model>HairFemale26<\/Model>\n\t\t\t\t<PaletteSelection_v8>\n\t\t\t\t\t<item>\n\t\t\t\t\t\t<PaletteSelection>Hair_Colour10<\/PaletteSelection>\n\t\t\t\t\t\t<PaletteMaterial>NativeMaterial<\/PaletteMaterial>\n\t\t\t\t\t<\/item>\n\t\t\t\t<\/PaletteSelection_v8>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>Helmet<\/Feature>\n\t\t\t\t<Model>Helmet_Female<\/Model>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>SkullCap<\/Feature>\n\t\t\t\t<Model>Skullcap_Female<\/Model>\n\t\t\t<\/item>\n\t\t<\/ModelSwapFeatures>\n\t\t<MorphFeatures>\n\t\t\t<item>\n\t\t\t\t<Feature>NoseWidthLess<\/Feature>\n\t\t\t\t<Weight>0.545342<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>NosePosition<\/Feature>\n\t\t\t\t<Weight>0.099191<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>NoseTipAngleUp<\/Feature>\n\t\t\t\t<Weight>0.744942<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>NoseBridge03<\/Feature>\n\t\t\t\t<Weight>0.500000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>NoseBridgeProfile01<\/Feature>\n\t\t\t\t<Weight>0.700000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>NoseTip02<\/Feature>\n\t\t\t\t<Weight>0.900000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>MouthWidth<\/Feature>\n\t\t\t\t<Weight>0.110317<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>UpperLipProfile01<\/Feature>\n\t\t\t\t<Weight>0.271655<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>MouthSerious<\/Feature>\n\t\t\t\t<Weight>0.903338<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>MouthPosDown<\/Feature>\n\t\t\t\t<Weight>0.026936<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>Complexion00Aged<\/Feature>\n\t\t\t\t<Weight>0.000000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>EyesIndifferent<\/Feature>\n\t\t\t\t<Weight>0.500000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>CheekbonesLarge<\/Feature>\n\t\t\t\t<Weight>0.900000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>JawSoft<\/Feature>\n\t\t\t\t<Weight>0.900000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>JawWidthLess<\/Feature>\n\t\t\t\t<Weight>0.200000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>ChinRound<\/Feature>\n\t\t\t\t<Weight>0.400000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>ChinWidthMore<\/Feature>\n\t\t\t\t<Weight>0.200000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>EyeWidth<\/Feature>\n\t\t\t\t<Weight>0.200000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>UpperEyeFold01<\/Feature>\n\t\t\t\t<Weight>0.100000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>BrowRound<\/Feature>\n\t\t\t\t<Weight>0.500000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>HeadWidth<\/Feature>\n\t\t\t\t<Weight>0.400000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>NeckThin<\/Feature>\n\t\t\t\t<Weight>0.300000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>EarsProminence<\/Feature>\n\t\t\t\t<Weight>0.900000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>EarsSloped<\/Feature>\n\t\t\t\t<Weight>0.400000<\/Weight>\n\t\t\t<\/item>\n\t\t\t<item>\n\t\t\t\t<Feature>Asymmetry03<\/Feature>\n\t\t\t\t<Weight>1.000000<\/Weight>\n\t\t\t<\/ite
